Test presentation
Ykiko/presentation pull request #1
Opened 2018-09-19 07:17 UTC by Ykiko

2018-09-20 05:44 UTC, koyif requested changes
Пока хватит. Как эти замечания пофиксишь, посмотрю дальше.

2018-09-20 05:44 UTC, koyif commented on src/main/java/com/example/conference/MyException/CoincidesTimeException.java
> +        super(errorName);
Для чего здесь поле error1?
Во-первых, почему добавлено "1"?
Во-вторых, ты наследуешься от Exception, который унаследован от Throwable. Внутри Throwable есть поле detailMessage, которое устанавливается через конструктор. Т.е. когда ты делаешь здаесь super(errorName), ты устанавливаешь значение для поля detailMessage. Получается, что у тебя одно и то же значение дублируется в твоем объекте.

2018-09-20 05:44 UTC, koyif commented on src/main/java/com/example/conference/MyException/CoincidesTimeException.java
> +    public String toString() {
Этот метод можно заменить аннотацией lombok ToString с параметром callSuper = true.

2018-09-20 05:44 UTC, koyif commented on src/main/java/com/example/conference/controller/PresentationController.java
> +                                   @ModelAttribute("room") Long roomId) throws Exception {
Не стоит указывать обобщенные типы исключений. Более правильный подход - перечислить все исключения, которые может породить этот метод.

2018-09-20 05:44 UTC, koyif commented on src/main/java/com/example/conference/service/PresentationService.java
> +    private String errorMessage9;
Из названия переменной должно быть понятно, для чего эта переменная нужна.
Вообще, непонятно зачем вытаскивать текст ошибок из конфига? Если для локализации, то в спринге есть уже механизм локализации.
В данном случае можно было просто сделать константами.
Если нужно именно вытаскивать из конфига, то сделай что-то вроде такого:
`@Value("${error.message.presentationNotFound}")`
`private String errorMessagePresentationNotFound;`

2018-09-20 05:44 UTC, koyif commented on src/main/java/com/example/conference/service/PresentationService.java
>          Date startdate = presentation.getStartdate();
Везде используй camelCase.

2018-09-20 05:44 UTC, koyif commented on src/main/java/com/example/conference/service/PresentationService.java
> +        if (!StringUtils.isEmpty(presentationName) && newRoom.isPresent()) {
Не стоит использовать newRoom.isPresent() и newRoom.get().
Просто вместо `Optional<Room> newRoom = roomRepository.findById(roomId);`
сделай `Room newRoom = roomRepository.findById(roomId).orElseThrow(() -> new RoomNotFoundException());`, например.

2018-09-20 05:44 UTC, koyif commented on src/main/java/com/example/conference/service/PresentationService.java
> +        if (!StringUtils.isEmpty(presentationName) && newRoom.isPresent()) {
Лучше проверить if (StringUtils.isEmpty(presentationName)) и выкинуть исключение, если имя пустое.
Тогда дальше код можно будет писать уже не в блоке условия и мы избавляемся от else. Т.е. сложность кода уменьшается: как алгоритмическая, так и для восприятия.

2018-09-20 05:44 UTC, koyif commented on src/main/java/com/example/conference/service/PresentationService.java
>              for (Presentation item : presentationRepository.findAll()) {
Зачем нам каждый раз пробегать по всем презентациям? А если их миллион?
Можно сделать выборку презентации на стороне БД. Просто сделай в репозитории метод, который ищет по названию презентации.
Тогда можно будет сделать проверку:
` if (presentationRepository.findByPresentationName(presentationName).isPresent()) {`
`throw new NoNamePresentationException("Error:" + errorMessage4);`
`}`

2018-09-20 05:44 UTC, koyif commented on src/main/java/com/example/conference/service/PresentationService.java
>              for (Presentation item : presentationRepository.findAll()) {
NoNamePresentationException - нехорошее название для исключения. Непонятно, когда оно происходит.
new PresentationAlreadyExistsException(presentationName) - более информативно.

2018-09-20 05:44 UTC, koyif commented on src/main/java/com/example/conference/service/PresentationService.java
> +                if (itemInterval.overlaps(currentIntervar) && expectedRoom.equals(presentation.getRoom())) {
А для этой проверки можно вытащить из БД только те презентации, которые запланированы на будущее в этой комнате.

2018-09-21 16:13 UTC, koyif requested changes

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/MyException/CoincidesTimeException.java
> +        super("CoincidesTimeException{" +
Зачем вот это? Просто передавай messageы super.

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/MyException/CoincidesTimeException.java
> +package com.example.conference.MyException;
Название пакета в camelCase не делается в java.

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/MyException/NoNameUserException.java
> +public class NoNameUserException extends Exception{
Когда выбрасывается это исключение? Когда юзер NoName?)))

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/MyException/NoNameUserException.java
> +public class NoNameUserException extends Exception{
Поправь названия, чтобы понятно было, когда именно выбрасываются твои исключения.

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/MyException/NoNameUserException.java
> +public class NoNameUserException extends Exception{
Помни, что после тебя с твоим кодом будут работать другие люди. И им должно быть все интуитивно понятно. Названия переменных, классов, методов...

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/controller/PresentationController.java
> +    public String AddPresentation(Model model) {
Уоу! Названия методов, полей и переменных всегда с маленькой буквы. Классов, интерфейсов, перечислений - с большой.

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/service/PresentationService.java
> +        Optional<Presentation> editPresentation = presentationRepository.findById(id);
Почему здесь не использовать orElseThrow?

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/service/PresentationService.java
> +    public void DeleteIdPresentation(@PathVariable("id") Long id) throws NotFoundException {
deletePresentation. Ты же не id удаляешь.

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/service/PresentationService.java
> +    public void UpdateSetPresentation(@PathVariable("id") Long id,
Что за PathVariable, ModelAttribute в сервисе? Это не контроллер!

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/service/PresentationService.java
> +        if (id != null) {
id вообще может здесь быть null? У тебя он в контроллере по умолчанию required.

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/service/RoomService.java
> +            for (Room item : roomRepository.findAll()) {
findByRoom. Зачем вытаскивать все?

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/service/RoomService.java
> +        throw new NoRoomException(errorMessageRoomIsRequired);
После else фигурные скобки, даже если после него один оператор.

2018-09-21 16:13 UTC, koyif commented on src/main/java/com/example/conference/service/RoomService.java
> +        if (id != null) {
Выше была такая же ситуация.

2018-09-25 06:56 UTC, koyif requested changes

2018-09-25 06:56 UTC, koyif commented on src/main/java/com/example/conference/controller/PresentationController.java
> +import com.example.conference.myException.*;
Зачем myExceptin? Просто exception

2018-09-25 06:56 UTC, koyif commented on src/main/java/com/example/conference/service/PresentationService.java
>      @Autowired
Почему здесь не используешь RequiredArgsConstructor?

2018-09-25 06:56 UTC, koyif commented on src/main/java/com/example/conference/service/RoomService.java
> +    public RoomService(RoomRepository roomRepository) {
И здесь RequiredArgsConstructor. Если я где-то делаю замечание, это не значит, что фиксить надо только то место, к которому относится замечание. Надо фиксить везде.

2018-09-25 06:56 UTC, koyif commented on src/main/java/com/example/conference/service/ScheduleService.java
> +    public ScheduleService(PresentationRepository presentationRepository, UserRepository userRepository) {
RequiredArgsConstructor

2018-09-25 06:56 UTC, koyif commented on src/main/java/com/example/conference/service/ScheduleService.java
> +        Optional<Presentation> schedule = presentationRepository.findById(id);
И снова orElseThrow. Какой смысл продолжать, если презентации не существует?

2018-09-25 06:56 UTC, koyif commented on src/main/java/com/example/conference/service/ScheduleService.java
> +            Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
Это лучше вынести в отдельный метод и использовать Optional.ofNullable().filter().map().orElseThrow(). Таким образом ты получишь либо имя, либо вылетит исключение и не надо будет столько if'ов.

2018-09-25 06:56 UTC, koyif commented on src/main/java/com/example/conference/service/ScheduleService.java
> +                Optional<User> userOptional = userRepository.findByUsername(username);
И снова orElseThrow. Если юзер не найден - это вообще очень исключительная ситуация и продолжать работу бессмысленно.
Я же уже два раза писал, что использовать Optional.isPresent() + Optional.get() - смертный грех.

2018-09-25 06:56 UTC, koyif commented on src/main/java/com/example/conference/service/ScheduleService.java
> +                        checkListener = true;
Зачем эта логическая переменная, если вместо нее можно сразу совершить действия, которые необходимы?

2018-09-25 06:56 UTC, koyif commented on src/main/java/com/example/conference/service/UserService.java
> +    @Autowired
RequiredArgsConstructor

2018-09-25 08:47 UTC, Ykiko commented on src/main/java/com/example/conference/service/ScheduleService.java
> +            Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
Да тут если заместо Optional использовать orElseThrow, половина if'ов сразу улетает

2018-09-25 13:39 UTC, koyif requested changes

2018-09-25 13:39 UTC, koyif commented on src/main/java/com/example/conference/service/UserService.java
> +        if (firstname.isEmpty() && lastname.isEmpty()) {
StringUtils.isAnyBlank(firstname, lastname)

2018-09-25 13:39 UTC, koyif commented on src/main/java/com/example/conference/service/UserService.java
> +        for (User item : userRepository.findAll()) {
findByFirstnameAndLastname

2018-09-25 13:39 UTC, koyif commented on src/test/java/com/example/conference/service/PresentationServiceTest.java
> +    void AddPresentation() throws Exception {
Названия методов с маленькой буквы.

2018-09-25 16:06 UTC, koyif requested changes

2018-09-25 16:06 UTC, koyif commented on src/main/java/com/example/conference/service/UserService.java
>              if (firstname.equals(item.getFirstname()) && lastname.equals(item.getLastname())) {
Это не лишняя проверка? Ты и так вытаскиваешь по фамилии и имени.

2018-09-25 16:06 UTC, koyif commented on src/main/java/com/example/conference/service/UserService.java
>              if (firstname.equals(item.getFirstname()) && lastname.equals(item.getLastname())) {
Кстати, а если однофамильцы будут и одноименцы?

2018-09-27 14:33 UTC, koyif requested changes

2018-09-27 14:33 UTC, koyif commented on src/main/java/com/example/conference/service/RoomService.java
> +        for (Room item : roomRepository.findByRoom(nameroom)) {
Есть смысл в этом цикле и нижележащем условии?

2018-09-27 16:47 UTC, koyif approved these changes

2018-09-27 16:47 UTC, merged